### ISSUE TITLE
txexpr modified incorrectly by run-txexpr

### ISSUE THREAD

**Issue by pmatos** [zyrolasting/polyglot#15]
In order to run things through `pygmentize` frog relies on `txexpr` having a certain format and `run-txexpr!` is chaging the format for no good reason.

Take a look:
```
Welcome to Racket v7.4 [cs].
> (require polyglot)
> (run-txexpr! (list '(pre ((class "brush: console")) (code "$ Tools/Scripts/build-jsc --jsc-only --debug\n...\n====================================================================\n JavaScriptCore is now built (02m:44s). \n===================================================================="))))
'((pre
   ((class "brush: console"))
   (code
    "$ Tools/Scripts/build-jsc --jsc-only --debug\n...\n====================================================================\n JavaScriptCore is now built (02m:44s). \n====================================================================")))
```

The problem here is that `(code () ...)` became `(code ...)` and lost its second element.

**Comment by zyrolasting** [comment]
@pmatos 

> The problem here is that (code () ...) became (code ...) and lost its second element.

I'm a little lost on this one because I don't see `(code () ...)` anywhere in your REPL session. I see a `(run-txexpr! (list '(pre ((class "brush: console")) (code "$ ...`, where a string follows immediately after code... And that appears in the output.

Can you show me a reproduction from `pygmentize`'s perspective?

**Comment by zyrolasting** [comment]
To your point, I do see the attribute list dropping only when it isn't empty. Investigating now.

```
> (run-txexpr! '((pre (code ((class "")) ""))))
'((pre (code ((class "")) "")))
> (run-txexpr! '((pre (code () ""))))
'((pre (code "")))
```

**Comment by zyrolasting** [comment]
@pmatos Root cause is a design decision by `txexpr` collection to not include empty lists when constructing tagged X-expressions attributes from parts.

From https://docs.racket-lang.org/txexpr/index.html?q=txexpr#%28def._%28%28lib._txexpr%2Fmain..rkt%29._txexpr%29%29
> Note that unlike xml->xexpr, if the attribute list is empty, it’s not included in the resulting expression.

The same applies to `splitf-txexpr`.

```
> (splitf-txexpr '(pre (code () "")) (λ _ #f) (λ _ _))
'(pre (code ""))
'()  
```

I can't replace this library on short notice, and forcing the presence of attribute lists in this project would cause similar problems for someone else. Are you able to include a normalization step where you need it to be?

**Comment by pmatos** [comment]
> Nvm, I do see the attribute list dropping only when it is empty. Investigating now.
> 
> ```
> > (run-txexpr! '((pre (code ((class "")) ""))))
> '((pre (code ((class "")) "")))
> > (run-txexpr! '((pre (code () ""))))
> '((pre (code "")))
> ```

That's correct. Apologies for the wrong quote when I opened the bug. My fault!

**Comment by pmatos** [comment]
> @pmatos Root cause is a design decision by the `txexpr` collection to not include empty attribute lists when constructing tagged X-expressions from parts.
> 
> From https://docs.racket-lang.org/txexpr/index.html?q=txexpr#%28def._%28%28lib._txexpr%2Fmain..rkt%29._txexpr%29%29
> 
> > Note that unlike xml->xexpr, if the attribute list is empty, it’s not included in the resulting expression.
> 
> The same applies to `splitf-txexpr`.
> 
> ```
> > (splitf-txexpr '(pre (code () "")) (λ _ #f) (λ _ _))
> '(pre (code ""))
> '()  
> ```
> 
> I can't replace this procedure on short notice, and forcing the presence of attribute lists in this project would cause similar problems for someone else. I took a look at `frog`'s source and saw why attribute lists must always be present. Are you able to add the empty attribute lists yourself after a call to `run-txexpr!`?

I have lots of changes to frog at this point, so I have ended up forking frog into a new project called Darwin (https://github.com/pmatos/darwin) because Greg is not actively maintaining frog any longer. I will fix this in Darwin instead. No action needed on your side. Thanks for the quick replies on these issues.
