### ISSUE TITLE
.literal doesn't include file in dist/

### ISSUE THREAD

**Issue by xy2iii** [zyrolasting/polyglot#35]
`.literal` allows to include an asset while preserving its original filename (and path??)
The path is correctly non-changed, but the asset isn't included in the `dist/` directory:
```
[my_resume.pdf.literal](Check out my resume!)
```
transforms into
```
<a href="my_resume.pdf">Check out my resume!</a>
```
However, because the resulting asset wasn't included in `dist`, the file isn't found.

**Comment by zyrolasting** [comment]
Based on my first read of this, this is intended behavior.

When you use a `.literal` link, it is no different than writing `<a href="my_resume.pdf">` straight into a vanilla HTML document. You are creating an exception to normal asset processing and telling Polyglot that it **should not do anything with the link and trust the file will appear in the distribution by some other means.**

If you've used Webpack, `.literal` links are similar to [marking `externals`](https://webpack.js.org/configuration/externals/). This is vital for supporting incompatible build processes, since it lets you create a contract of sorts between your project and the _output_ of another project. [See this example in the docs](https://docs.racket-lang.org/polyglot/multiple-workflows.html#%28part._.Use__literal_to_.Mark_.External_.Dependencies%29).

That all being said, let's fix your problem. If your intention is to reference a file and copy it to the dist directory without changing the name, then you need to specify that (as you know Polyglot's base workflow is biased towards cache-busting and will rename the file).

Here's a couple of options.

First, you can tell your workflow in `.polyglotrc.rkt` to copy files as-is.

```
#lang racket/base

(provide polyglot+%)
(require polyglot)

(define (copy-as-is clear compiler)
  (define dest (dist-rel (file-name-from-path clear)))
  (copy-file clear dest #:exists-ok? #t)
  dest)

(define polyglot+%
  (class polyglot/functional%
    (define (delegate clear)
      (case (path-get-extension clear)
        [(#".pdf") copy-as-is]
        [else (super delegate clear)]))))
```

Second, if you only intend to do this as a one-off, you can fulfill the PDF on the spot alongside your link in the page.

```
[my_resume.pdf.literal](Check out my resume!)

<script type="application/racket">
#lang racket/base
(require polyglot)
(copy-file "/path/to/resume.pdf" (dist-rel "my_resume.pdf"))
</script>
```

**Comment by zyrolasting** [comment]
Closing out due to inactivity. Please reopen if you have a follow-up.
